Classifiers caused some problems during releasing (wtf), removed them.
When running:

    python setup.py sdist bdist_wheel upload

I've got this error:

    ...
    running upload
    Traceback (most recent call last):
      File "setup.py", line 52, in <module>
        'Programming Language :: Python :: 3',
      File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/command/upload.py", line 63, in run
        self.upload_file(command, pyversion, filename)
      File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/command/upload.py", line 161, in upload_file
        body.write(value)
    TypeError: a bytes-like object is required, not 'str'

Removing classifiers solved the problem. I have no idea why and I have no time
to dig deeper.